name: Update Star List

on:
  schedule:
    - cron: '0 2 * * *' # 每天 UTC 2点自动运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install starred
        run: pip install starred

      - name: Generate Star List
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          starred --username VancySavoki --sort > STARRED.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add STARRED.md
          git commit -m "Update star list" || echo "No changes to commit"
          git push